Repository rht-labs/enablement-docs, pull requests merged in 2021-03, with the labels that each got.

#577 Feature/readme
  README.md
  slides/package.json
Labels: enhancement

#571 Review D0500 Slides for activities in day 2
  slides/Configuration-as-Code.html
  slides/configuration-as-code.html
  slides/images/kanban/kanban-littles-law.png
  slides/images/kanban/toyota-production-system.png
  slides/kanban.html
  slides/markdown/kanban.md
  slides/markdown/scrum.md
Labels: enhancement

#574 Review D0500 Slides for activities in day 4
  slides/empathy-mapping.html
  slides/markdown/empathy_mapping.md
Labels: enhancement

#575 Review D0500 Slides for activities in day 5
  slides/delivery-showcase-demo-day.html
  slides/images/open-practice-library-logo.png
  slides/images/open-practice-library.png
  slides/markdown/delivery_showcase_demo_day.md
  slides/markdown/open_practice_library.md
  slides/open-practice-library.html
Labels: enhancement, facilitator-enablement

#596 Clarify ocp token retrieve instructions
  exercises/1-the-manual-menace/README.md
  exercises/images/exercise1/api-login-token-0.png
Labels: quick-fix

#573 Review D0500 Slides for activities in day 3
  slides/automated-testing-part-1.html
  slides/automated-testing-part-2.html
  slides/ci-cd-cd.html
  slides/markdown/automated_testing_part_1.md
  slides/markdown/continuous_integration_continuous_delivery_continuous_deployment.md
  slides/markdown/pipelines_as_code.md
  slides/markdown/user_story_mapping.md
  slides/pipelines-as-code.html
  slides/user-story-mapping.html
Labels: enhancement
